### ISSUE TITLE
詳細な使用方法などはありますか？

### ISSUE THREAD

**Issue by rikusen0335** [bit-trade-one/RasPi-Zero-One-Series#7]
こんにちは。突然Issueを開くこと、申し訳ありません。
当方電子回路には疎く、あまり使い方がよくわからず突発的に買ってしまったため、現在どのように使えばよいかわからず途方に暮れている状態です。
なので、もしあればそちらを提示してはいただけないでしょうか？また、node-redを使用して使えるのでしょうか？複数の質問があり申し訳ないですが、よろしくおねがいします。

**Comment by takeokk** [comment]
こんにちは。
ゼロワンシリーズ内でも製品によって大分違いがありますので、一概にお答えする事が出来ず……
製品によってはnode-redを含めた詳細な作例記事をUPしているものもございます。
http://bit-trade-one.co.jp/blog/category/iotpost/
こちらのカテゴリ一覧をご参照下さい。

**Comment by rikusen0335** [comment]
おっと、申し訳ないです。ADRSZIRSを購入させていただきました。一応node-redを使用してではないですが使用方法はわかったので、おそらく大丈夫だと思います。失礼しました。
